## Python Basic Programming Exercises

Q1: What is the output of following expression
    5 + 4 * 9 % (3 + 1) / 6 - 1

In [ ]:
5 + 4 * 9 % (3 + 1) / 6 - 1

4.0

Q2: Write a program to check if a Number is Odd or Even. Take number as a input from user at runtime.

In [ ]:
# Python program to check if a number is odd or even

# Take input from the user
number = int(input("Enter a number: "))

# Check if the number is even or odd
if number % 2 == 0:
    print(f"{number} is Even.")
else:
    print(f"{number} is Odd.")

Enter a number: 4
4 is Even.

Q3: Write a program to display the multiplication table by taking a number as input.
    [Hint : Use print statement inside of a loop]

In [ ]:
# Python program to display the multiplication table of a number

# Take input from the user
number = int(input("Enter a number: "))

# Loop to generate the multiplication table
for i in range(1, 11):
    print(f"{number} x {i} = {number * i}")

Enter a number: 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

Q4: Write a program which will find all numbers between 2000 and 3200 which are divisible by 7
    but are not a multiple of 5.

Note: The numbers obtained should be printed in a comma-separated sequence on a single line.

In [ ]:
# Python program to find numbers divisible by 7 but not a multiple of 5

# List to store the numbers
numbers = []

# Loop through the range 2000 to 3200 (inclusive)
for i in range(2000, 3201):
    if i % 7 == 0 and i % 5 != 0:
        numbers.append(str(i))

# Join the list into a comma-separated string and print it
print(", ".join(numbers))

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199

Q5: Count the elements of each datatype inside the list and display in output
    [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

In [ ]:
# Python program to count elements of each data type in a list

# Given list
data = [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

# Dictionary to store the count of each data type
type_counts = {}

# Loop through each element in the list
for element in data:
    # Get the data type of the element
    element_type = type(element)

    # If the type is already in the dictionary, increment the count
    if element_type in type_counts:
        type_counts[element_type] += 1
    # Otherwise, add the type to the dictionary with a count of 1
    else:
        type_counts[element_type] = 1

# Display the results
for element_type, count in type_counts.items():
    print(f"{element_type.__name__}: {count}")

int: 5
str: 4
float: 1
bool: 1
NoneType: 1

Q6: Add all values from the list with numeric datatypes
    [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

In [ ]:
# Python program to add all numeric values from the list

# Given list
data = [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

# Variable to store the sum of numeric values
total_sum = 0

# Loop through each element in the list
for element in data:
    # Check if the element is of numeric type (int, float, bool)
    if isinstance(element, (int, float)):
        total_sum += element

# Display the result
print(f"The sum of all numeric values is: {total_sum}")

The sum of all numeric values is: 22.5

Q7: Concat all str datatypes with hyphen as a delimiter
    [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

In [ ]:
# Python program to concatenate all string values with a hyphen as a delimiter

# Given list
data = [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

# List to store all string values
string_values = []

# Loop through each element in the list
for element in data:
    # Check if the element is a string
    if isinstance(element, str):
        string_values.append(element)

# Concatenate the strings with a hyphen as a delimiter
result = "-".join(string_values)

# Display the result
print(f"The concatenated string is: {result}")

The concatenated string is: Py-10-SQL-John

Q8: Write a UDF that takes list as input and returns sum of all numbers
    (exclude bool) and count of all str
    [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]

Hint:
-----
def my_func:
    # your code

my_func(l1)
# output --> {'Sum': xxx, 'Count_of_Strs': xxx}

In [ ]:
# Define the UDF
def my_func(data):
    # Initialize variables
    total_sum = 0
    str_count = 0

    # Loop through each element in the list
    for element in data:
        # Check if the element is a number (int, float) but not a bool
        if isinstance(element, (int, float)) and not isinstance(element, bool):
            total_sum += element
        # Check if the element is a string
        elif isinstance(element, str):
            str_count += 1

    # Return the results as a dictionary
    return {'Sum': total_sum, 'Count_of_Strs': str_count}

# Example usage
l1 = [2, 3, 'Py', '10', 1, 'SQL', 5.5, True, 3, 'John', None, 7]
result = my_func(l1)
print(result)

{'Sum': 21.5, 'Count_of_Strs': 4}

Q9: Get only odd numbers from the following list and store the numbers in new list
    li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]

    i. Use loops to get the answer
   ii. Use list comprehensions
  iii. Use lambda function with filter

In [ ]:
# Using a loop to get odd numbers
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]

odd_numbers_loop = []

for num in li:
    if num % 2 != 0:
        odd_numbers_loop.append(num)

print("Odd numbers using loop:", odd_numbers_loop)


# Using list comprehensions to get odd numbers
odd_numbers_list_comp = [num for num in li if num % 2 != 0]

print("Odd numbers using list comprehension:", odd_numbers_list_comp)


# Using lambda function with filter to get odd numbers
odd_numbers_lambda = list(filter(lambda x: x % 2 != 0, li))

print("Odd numbers using lambda with filter:", odd_numbers_lambda)

Odd numbers using loop: [5, 7, 97, 77, 23, 73, 61]
Odd numbers using list comprehension: [5, 7, 97, 77, 23, 73, 61]
Odd numbers using lambda with filter: [5, 7, 97, 77, 23, 73, 61]

Q10: Write a UDF to return the descriptives [sum, count, min, mean, max] for a list of n number of input
    numbers.

In [ ]:
# Define the UDF to calculate descriptives
def calculate_descriptives(numbers):
    # Calculate sum
    total_sum = sum(numbers)

    # Calculate count
    count = len(numbers)

    # Calculate minimum
    minimum = min(numbers)

    # Calculate mean
    mean = total_sum / count if count > 0 else 0

    # Calculate maximum
    maximum = max(numbers)

    # Return the descriptives as a dictionary
    return {
        'Sum': total_sum,
        'Count': count,
        'Min': minimum,
        'Mean': mean,
        'Max': maximum
    }

# Example usage
numbers_list = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]
descriptives = calculate_descriptives(numbers_list)
print(descriptives)

{'Sum': 481, 'Count': 10, 'Min': 5, 'Mean': 48.1, 'Max': 97}

Q11: Write an udf to calculate the area of different shapes

Take shape and dimensions as arguments to udf as follows :

1. square which has side
2. rectangle which has length and width
3. circle which has radius

The shape should be a positional argument and it's dimensions are taken as kwargs

Perform proper validation for the user inputs and then calculate area.

E.g. if shape is square, ensure kwargs has "side" and if so, then you may return the area, else display appropriate error message like "Please enter 'side' for a square"

In [ ]:
import math

# Define the UDF to calculate the area of different shapes
def calculate_area(shape, **kwargs):
    shape = shape.lower()

    if shape == 'square':
        # Validate that 'side' is provided
        if 'side' in kwargs:
            side = kwargs['side']
            if isinstance(side, (int, float)) and side > 0:
                return side * side
            else:
                return "Please enter a positive numeric value for 'side'."
        else:
            return "Please enter 'side' for a square."

    elif shape == 'rectangle':
        # Validate that 'length' and 'width' are provided
        if 'length' in kwargs and 'width' in kwargs:
            length = kwargs['length']
            width = kwargs['width']
            if all(isinstance(dim, (int, float)) and dim > 0 for dim in [length, width]):
                return length * width
            else:
                return "Please enter positive numeric values for 'length' and 'width'."
        else:
            return "Please enter both 'length' and 'width' for a rectangle."

    elif shape == 'circle':
        # Validate that 'radius' is provided
        if 'radius' in kwargs:
            radius = kwargs['radius']
            if isinstance(radius, (int, float)) and radius > 0:
                return math.pi * radius * radius
            else:
                return "Please enter a positive numeric value for 'radius'."
        else:
            return "Please enter 'radius' for a circle."

    else:
        return "Invalid shape. Please choose either 'square', 'rectangle', or 'circle'."

# Example usage
print(calculate_area('square', side=4))
print(calculate_area('rectangle', length=5, width=3))
print(calculate_area('circle', radius=7))
print(calculate_area('square'))  # Error case
print(calculate_area('rectangle', length=5))  # Error case
print(calculate_area('circle', diameter=7))  # Error case
print(calculate_area('triangle', base=5, height=3))  # Invalid shape

16
15
153.93804002589985
Please enter 'side' for a square.
Please enter both 'length' and 'width' for a rectangle.
Please enter 'radius' for a circle.
Invalid shape. Please choose either 'square', 'rectangle', or 'circle'.

Q12: Write a UDF to reconcile the values within two lists.
    l1 = ['January', 'February', 'March', 'May', 'June', 'September', 'December']
    l2 = ['January', 'February', 'April', 'June', 'October', 'December']

Hint:
-----
def func(l1, l2):
    your code here...

Output:
{'Matched': ['January', 'February', 'June', 'December'],
    'Only in l1': ['March', 'May', 'September'],
        'Only in l2': ['April', 'October']}

In [ ]:
def reconcile_lists(l1, l2):
    # Convert lists to sets for easier set operations
    set1 = set(l1)
    set2 = set(l2)

    # Find matched values (intersection)
    matched = list(set1.intersection(set2))

    # Find values only in l1 (difference)
    only_in_l1 = list(set1.difference(set2))

    # Find values only in l2 (difference)
    only_in_l2 = list(set2.difference(set1))

    # Return results as a dictionary
    return {
        'Matched': sorted(matched),
        'Only in l1': sorted(only_in_l1),
        'Only in l2': sorted(only_in_l2)
    }

# Example usage
l1 = ['January', 'February', 'March', 'May', 'June', 'September', 'December']
l2 = ['January', 'February', 'April', 'June', 'October', 'December']
result = reconcile_lists(l1, l2)
print(result)

{'Matched': ['December', 'February', 'January', 'June'], 'Only in l1': ['March', 'May', 'September'], 'Only in l2': ['April', 'October']}

Q13: write a UDF to check if a number is prime or not.

In [ ]:
def is_prime(number):
    # Check if the number is less than 2 (not prime)
    if number <= 1:
        return False

    # Check if the number is 2 or 3 (both prime)
    if number <= 3:
        return True

    # Eliminate multiples of 2 and 3
    if number % 2 == 0 or number % 3 == 0:
        return False

    # Check divisibility from 5 to sqrt(number)
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6

    return True

# Example usage
print(is_prime(2))    # True
print(is_prime(4))    # False
print(is_prime(29))   # True
print(is_prime(100))  # False

True
False
True
False

Q14. Write a program which can compute the factorial of a given numbers.
#   The results should be printed in a comma-separated sequence on a single line.
# input() function can be used for getting user(console) input


#Suppose the input is supplied to the program:  8
#Then, the output should be:  40320
#Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [ ]:
import math

# Function to compute the factorial
def compute_factorial(n):
    return math.factorial(n)

# Function to process a list of inputs
def process_factorials(inputs):
    results = []
    for value in inputs:
        try:
            number = int(value)
            if number < 0:
                results.append(f"Factorial is not defined for negative numbers.")
            else:
                result = compute_factorial(number)
                results.append(result)
        except ValueError:
            results.append("Invalid input. Please enter a valid integer.")
    return results

# Get user input
user_input = input("Enter numbers separated by commas: ")

# Split the input into a list of strings
input_list = user_input.split(',')

# Process the list of inputs
factorial_results = process_factorials(input_list)

# Print the results in a comma-separated sequence
print(', '.join(map(str, factorial_results)))

Enter numbers separated by commas: 1,2,3,4,5
1, 2, 6, 24, 120

Q15. With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.

#Suppose the following input is supplied to the program: 8
#Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
#Hints: In case of input data being supplied to the question, it should be assumed to be a console input. Consider using dict()

In [ ]:
def generate_square_dict(n):
    # Generate a dictionary where keys are integers and values are their squares
    square_dict = {i: i * i for i in range(1, n + 1)}
    return square_dict

# Get user input
try:
    # Read input from the user
    user_input = int(input("Enter an integer: "))

    # Check if the input is a positive integer
    if user_input < 1:
        print("Please enter a positive integer greater than 0.")
    else:
        # Generate and print the dictionary
        result = generate_square_dict(user_input)
        print(result)
except ValueError:
    print("Invalid input. Please enter a valid integer.")

Enter an integer: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

Q16. Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
#Suppose the following input is supplied to the program: 34,67,55,33,12,98
    #Then, the output should be: ['34', '67', '55', '33', '12', '98'] ('34', '67', '55', '33', '12', '98')

#Hints: In case of input data being supplied to the question, it should be assumed to be a console input. you may use tuple() method to convert list to tuple

In [ ]:
def generate_list_and_tuple(input_string):
    # Split the input string into a list of numbers
    number_list = input_string.split(',')

    # Convert the list to a tuple
    number_tuple = tuple(number_list)

    return number_list, number_tuple

# Get user input
user_input = input("Enter a sequence of comma-separated numbers: ")

# Generate list and tuple
list_result, tuple_result = generate_list_and_tuple(user_input)

# Print the results
print(list_result)
print(tuple_result)

Enter a sequence of comma-separated numbers: 3,4,5
['3', '4', '5']
('3', '4', '5')

Q17. Write a program that accepts a comma separated sequence of words as input and
# prints the words in a comma-separated sequence after sorting them alphabetically.

# Suppose the following input is supplied to the program: without,hello,bag,world
# Then, the output should be: bag,hello,without,world

#Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [ ]:
def sort_words_alphabetically(input_string):
    # Split the input string into a list of words
    words_list = input_string.split(',')

    # Sort the list of words alphabetically
    sorted_words = sorted(words_list)

    # Join the sorted list into a comma-separated string
    sorted_words_string = ','.join(sorted_words)

    return sorted_words_string

# Get user input
user_input = input("Enter a sequence of comma-separated words: ")

# Process and print the sorted words
sorted_words = sort_words_alphabetically(user_input)
print(sorted_words)

Enter a sequence of comma-separated words: hello, apple, boy
 apple, boy,hello

Q18. Write a program that accepts a sequence of whitespace separated words
# as input and prints the words after removing all duplicate words and sorting them alphanumerically.
# Suppose the following input is supplied to the program: hello world and practice makes perfect and hello world again
# Then, the output should be: again and hello makes perfect practice world

#Hints: In case of input data being supplied to the question, it should be assumed to be a console input.
#We use set container to remove duplicated data automatically and then use sorted() to sort the data.

In [ ]:
def process_words(input_string):
    # Split the input string into a list of words
    words_list = input_string.split()

    # Remove duplicate words by converting the list to a set
    unique_words = set(words_list)

    # Sort the unique words alphabetically
    sorted_words = sorted(unique_words)

    # Join the sorted words into a whitespace-separated string
    sorted_words_string = ' '.join(sorted_words)

    return sorted_words_string

# Get user input
user_input = input("Enter a sequence of whitespace-separated words: ")

# Process and print the result
result = process_words(user_input)
print(result)

Enter a sequence of whitespace-separated words: hello boy kese ho
boy hello ho kese

Q19. Write a program that accepts a sentence and calculate the number of upper case
# letters and lower case letters.
#Suppose the following input is supplied to the program: Hello world!
#Then, the output should be: UPPER CASE 1 LOWER CASE 9

#Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [ ]:
def count_case_letters(sentence):
    # Initialize counters for uppercase and lowercase letters
    upper_case_count = 0
    lower_case_count = 0

    # Iterate through each character in the sentence
    for char in sentence:
        if char.isupper():
            upper_case_count += 1
        elif char.islower():
            lower_case_count += 1

    return upper_case_count, lower_case_count

# Get user input
user_input = input("Enter a sentence: ")

# Count uppercase and lowercase letters
upper_count, lower_count = count_case_letters(user_input)

# Print the results
print(f"UPPER CASE {upper_count} LOWER CASE {lower_count}")

Enter a sentence: hLodfdf
UPPER CASE 1 LOWER CASE 6

Q20. Write a program that takes a string and returns reversed string. i.e. if input is "abcd123" output should be "321dcba"

In [ ]:
def reverse_string(s):
    # Reverse the string using slicing
    return s[::-1]

# Get user input
user_input = input("Enter a string: ")

# Reverse the string
reversed_string = reverse_string(user_input)

# Print the reversed string
print(reversed_string)

Enter a string: gracious
suoicarg